[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate"
  status = 200
  force = true
[[redirects]]
  from = "/api/photo-to-text"
  to = "/.netlify/functions/photo-to-text"
  status = 200
  force = true
