[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate"
  status = 200
  force = true
[[redirects]]
  from = "/api/photo-to-text"
  to = "/.netlify/functions/photo-to-text"
  status = 200
  force = true
[[redirects]]
  from = "/api/generate-image-quiz"
  to = "/.netlify/functions/generate-image-quiz"
  status = 200
  force = true
[[redirects]]
  from = "/api/summarize-notes-image"
  to = "/.netlify/functions/summarize-notes-image"
  status = 200
  force = true
[[redirects]]
  from = "/api/notes-to-bullets-image"
  to = "/.netlify/functions/notes-to-bullets-image"
  status = 200
  force = true
[[redirects]]
  from = "/api/generate-flashcards-image"
  to = "/.netlify/functions/generate-flashcards-image"
  status = 200
  force = true
